### ISSUE TITLE
comment on the website

### ISSUE THREAD

**Issue by artemD7** [romizb/romizb.github.io#2]
Hi,
The website is very nice, but the links for your email and Linkedin profile give "404 file not found". In your code it is written correctly, so maybe it is some intenal github problem?  Probably, the email adress you can write as just a bold text (not a link) and for the LinkedinPage  - maybe try do delete this small icon which you have in your code before [linkedin]. So 🔗 [linkedin](www.linkedin.com/in/romi-brody) will become [linkedin](www.linkedin.com/in/romi-brody). Maybe this small icon is related to the glitch? 

@liroh99

**Comment by romizb** [comment]
Thank you for the insightful input!
After some tinkering I managed to fix the linkedin and email links.
The site is now elevated!
